# run: conda env create --file environment.yml
name: binder-env
dependencies:
- python==3.8.18
- anaconda
- fiona==1.9.4
- geopandas==0.13.2
- mapbox_earcut==1.0.1
- pydeck==0.8.0	
- topojson==1.7
- pip
#- numpy=1.13.3  # pin version for conda
- pip:
  # works for regular pip packages
  #- docx
  #- gooey
  #- matplotlib==2.0.0  # pin version for pip
  # and for wheels
  #- http://www.lfd.uci.edu/~gohlke/pythonlibs/bofhrmxk/opencv_python-3.1.0-cp35-none-win_amd64.whl
  - triangle==20230923	 #- python wrapper around Jonathan Richard Shewchuk's at rufat.be/triangle
  - cjio==0.7.3	         #- python CLI to process and manipulate CityJSON files
  - overpass==0.7	
  - osm2geojson==0.2.4
  - openlocationcode==1.0.1	 #- google 'plus codes' at https://github.com/google/open-location-code
